require("nvim.options")
require("nvim.keymaps")
require("nvim.plugins")
require("nvim.autocommands")
require("nvim.colorizer")
require("nvim.cmp")
require("nvim.telescope")
require("nvim.gitsigns")
require("nvim.treesitter")
require("nvim.autopairs")
require("nvim.comment")
require("nvim.nvim-tree")
require("nvim.lualine")
require("nvim.toggleterm")
require("nvim.project")
require("nvim.spectre")
require("nvim.lsp")
require("nvim.dap")
require("nvim.venn")
require("nvim.autotag")
require("nvim.httui")
require("nvim.colorscheme")
require("nvim.ai")

-- require("nvim.fsharp")
-- require("nvim.neorg")
-- require("nvim.elixir")
